rules:
  grandfathered:
    regex:
      - "grandfathered"
    level: failure
  sanity_check:
    regex:
      - "sanity[_-]*check"
    level: failure
  man_hours:
    regex:
      - "man[_-]*hours"
    level: failure
    
